### Jupyter Notebooks

São ambientes executáveis para scripts python **focados em ciência de dados, machine learning e experimentos**. É comum o seu uso em etapas de teste e validação de novos modelos de machine learning ou pipeline de dados.

Um notebook possui uma estrutura dividida em **células executáveis**. Cada célula pode conter scripts python e ser executada isoladamente. Também é possível escrever markdowns, como no exemplo desta célula.

Por esse motivo é necessário **atenção em relação a ordem de execução das células**.

É bastante flexível e o motivo por ter essa estrutura é justamente para servir como um ambiente de experimentação.

**Menu**: Logo acima é possível visualizar as opções de executar uma célula, criar uma nova célula e reiniciar o kernel. O kernel é ambiente usado pelo notebook para executar localmente, como se fosse um servidor. É necessário escolher qual ambiente python será usado pelo kernel. Assim que você abrir o seu notebook, uma opção estará disponível no canto superior direito com o nome "Select Kernel".

### Pandas

É a biblioteca mais popular para **extração, análise, processamento, transformação e carregamento de dados**. Possui uma sintaxe intuitiva, o que garante uma inicialização rápida no ambiente. O Pandas possui suporte para praticamente todas as "fontes" de dados, como: arquivos excel (csv, xlsx), bancos de dados, serviços externos de storage e outros.

Por ser uma biblioteca python, é muito utilizada para a criação de **pipelines de dados e scripts de I.A e machine learning**. Possui uma estrutura de dados própria, chamada de **DataFrame** que será vista a seguir.

In [1]:
import pandas as pd

### Extração

In [2]:
'''
Exemplo de carregamento de um conjunto de dados em formato .csv
'''

iris = pd.read_csv("../data/flores_iris.csv")

In [3]:
'''
Visualizando os primeios dados da planilha
'''
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

**Obervações**: O separador do seu arquivo pode ser vírgula (,) ou ponto e vírgula (;). Por padrão o `read_csv()` utiliza a vírgula. Mas existe também a opção `read_xlsx()` que possui como padrão o ponto e vígular. Caso o arquivo seja um .csv mas mesmo assim utilize o ponto é vírgula, é possível usar um parâmetro que informa o separador.

`read_csv('flores_iris.csv', sep=';')`

**Documentação do pandas**: https://pandas.pydata.org/docs/reference/index.html

### DataFrame

A extração feita anteriormente com o arquivo csv gerou um **objeto chamado DataFrame**. É a estrutura de dados usada pelo pandas e que representa uma tabela. Todas as operações são feitas nessas tabelas. O DataFrame é composto por outros objetos chamados de **Series**, que representam as colunas da tabela.

É possível criar um DataFrame usando dicionários do python:

In [7]:
'''
O dicionário representa o DataFrame.
Cada lista dentro do dicionário representa uma Serie.
'''
df = pd.DataFrame(
    {
        "Name": [
            "Fulano da Silva",
            "Ciclano José"
        ],
        "Idade": [35, 44],
        "Profissão": ["Programador", "Analista de Dados"]
    }
)

In [8]:
df

              Name  Idade          Profissão
0  Fulano da Silva     35        Programador
1     Ciclano José     44  Analista de Dados

In [ ]:
'''Visualizando os tipos'''
print(type(df))
print(type(df['Name']))#

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

Na sintaxe do Pandas usamos os colchetes "[]" para retornar uma Series. Também é usado para filtragem e outras operações como vamos ver mais a frente.

A partir de uma Series podemos chamar métodos para extrair informações. [Métodos disponíveis](https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series)

In [12]:
# Retorna o maior valor da coluna
#df["Idade"].max()
# Número de valores não nulos
#df["Idade"].count()
# Estatísticas gerais
df["Idade"].describe()

count     2.000000
mean     39.500000
std       6.363961
min      35.000000
25%      37.250000
50%      39.500000
75%      41.750000
max      44.000000
Name: Idade, dtype: float64

In [13]:
df.dtypes

Name         object
Idade         int64
Profissão    object
dtype: object

In [14]:
# Selecionando subconjunto de colunas
sample = iris[['SepalLengthCm', 'SepalWidthCm']]
sample

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [17]:
# Filtrando DataFrame usando uma condição
sample_filter = iris[iris['SepalLengthCm']>5]
sample_filter

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [18]:
#Obetendo apenas a coluna mas com o mesmo filtro
col = iris['SepalLengthCm']>5
col

0       True
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: SepalLengthCm, Length: 150, dtype: bool

In [19]:
# Obtendo média dos valores de uma coluna
iris['SepalLengthCm'].mean()

np.float64(5.843333333333334)

In [21]:
# iloc é um método onde buscamos uma linha pelo índice
sample_iloc = iris.iloc[3]
sample_iloc

Id                         4
SepalLengthCm            4.6
SepalWidthCm             3.1
PetalLengthCm            1.5
PetalWidthCm             0.2
Species          Iris-setosa
Name: 3, dtype: object

In [22]:
type(sample_iloc)

pandas.core.series.Series

In [23]:
# Já o loc nos permite passar linha e coluna, fazendo filtros mais complexos
sample_loc = iris.loc[(iris['SepalLengthCm']>5) & (iris['SepalWidthCm']>3)]
sample_loc

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
16,17,5.4,3.9,1.3,0.4,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
19,20,5.1,3.8,1.5,0.3,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
21,22,5.1,3.7,1.5,0.4,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
31,32,5.4,3.4,1.5,0.4,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
36,37,5.5,3.5,1.3,0.2,Iris-setosa
39,40,5.1,3.4,1.5,0.2,Iris-setosa
44,45,5.1,3.8,1.9,0.4,Iris-setosa
46,47,5.1,3.8,1.6,0.2,Iris-setosa
48,49,5.3,3.7,1.5,0.2,Iris-setosa
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica

In [21]:
'''
DataSet filtrado com apenas comprimento e largura da sépala.
Usando método describe() para obter as estatísticas dessas variáveis
'''
iris[['SepalLengthCm', 'SepalWidthCm']].describe()

       SepalLengthCm  SepalWidthCm
count     150.000000    150.000000
mean        5.843333      3.054000
std         0.828066      0.433594
min         4.300000      2.000000
25%         5.100000      2.800000
50%         5.800000      3.000000
75%         6.400000      3.300000
max         7.900000      4.400000

In [25]:
'''
value_counts(): Volume de dados para cada valor/classe
value_counts(normalize=True): Em formato de porcentagem
'''
iris['Species'].value_counts(normalize=True)

Species
Iris-setosa        0.333333
Iris-versicolor    0.333333
Iris-virginica     0.333333
Name: proportion, dtype: float64

In [26]:
'''
Renomeando as colunas
Retorna um novo DataFrame se o parâmetro 'inplace=False'
'''

exportar_setosa = iris.rename(
    columns={
        "SepalLengthCm": "ComprimentoSepala",
        "SepalWidthCm": "LarguraSepala",
        "PetalLengthCm": "ComprimentoPetala",
        "PetalWidthCm": "LarguraPetala",
        "Species": "Classe"
        })
exportar_setosa

,Id,ComprimentoSepala,LarguraSepala,ComprimentoPetala,LarguraPetala,Classe
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [27]:
'''Apenas Iris Setosa'''
exportar_setosa['Classe']=="Iris-setosa"

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: Classe, Length: 150, dtype: bool

In [28]:
exportar_setosa = exportar_setosa[exportar_setosa['Classe']=="Iris-setosa"]

In [29]:
'''Exporta para csv'''
exportar_setosa.to_csv("iris_setosa.csv")